name: mek snek

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  snek:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate snek
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snek.svg
            dist/dark-snek.svg?palette=github-dark
            dist/snek.gif
            dist/dark-snek.gif?palette=github-dark
      - name: push snek to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snek
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}